author: Microsoft
author_url: https://azure.github.io/azure-sdk/
github_url: https://github.com/Azure/azure-sdk-for-ios
module: AzureMapsRender
module_version: 1.0.0
readme: ../sdk/AzureMapsRender/AzureMapsRender/README.md
skip_undocumented: false
theme: fullwidth
output: ../build/jazzy/AzureMapsRender
swift_build_tool: spm
clean: true
sdk: iphonesimulator
xcodebuild_arguments:
  - "-workspace"
  - "AzureSDK.xcworkspace"
  - "-scheme"
  - "AzureMapsRender"
  - "-sdk"
  - "iphonesimulator"
  - "-arch"
  - "x86_64"
exclude:
  - "*/Source/ObjectiveCCompatibility/*"
  - "*/Tests/*"
